site_name: astdoc
site_author: daizutabi
site_description: astdoc.
site_url: https://daizutabi.github.io/astdoc/
repo_url: https://github.com/daizutabi/astdoc/
repo_name: daizutabi/astdoc
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
plugins:
  - search:
  - mkapi:
      enabled: true
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - astdoc: index.md
  - Reference:
      - $api:src/astdoc.***
